services:
  php:
    image: tugboatqa/php:8.1-apache
    default: true
    depends: mysql
    environment:
      DOCROOT: /var/www/html
    commands:
      init:
        - apt-get update
        - apt-get install -y libzip-dev
        - docker-php-ext-install mysqli zip
        - curl -sS -o /usr/local/bin/wp https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        - chmod +x /usr/local/bin/wp
        - printf "[client]\nssl-mode=DISABLED\n" > /root/.my.cnf
      update:
        - ln -snf "${TUGBOAT_ROOT}/web" "${DOCROOT}"
        - mkdir -p "${DOCROOT}/wp-content/uploads" || /bin/true
        - chgrp -R www-data "${DOCROOT}/wp-content/uploads"
        - find "${DOCROOT}/wp-content/uploads" -type d -exec chmod 2775 {} \;
        - find "${DOCROOT}/wp-content/uploads" -type f -exec chmod 0664 {} \;
        # Create wp-config.php specific for Tugboat
        - cp ${DOCROOT}/wp-config-sample.php ${DOCROOT}/wp-config-tugboat.php
        - sed -i "s/database_name_here/tugboat/g" ${DOCROOT}/wp-config-tugboat.php
        - sed -i "s/username_here/tugboat/g" ${DOCROOT}/wp-config-tugboat.php
        - sed -i "s/password_here/tugboat/g" ${DOCROOT}/wp-config-tugboat.php
        - sed -i "s/localhost/mysql/g" ${DOCROOT}/wp-config-tugboat.php
        # Dynamic URLs for Tugboat
        - echo "define('WP_HOME', 'https://' . \$_SERVER['HTTP_HOST']);" >> ${DOCROOT}/wp-config-tugboat.php
        - echo "define('WP_SITEURL', 'https://' . \$_SERVER['HTTP_HOST']);" >> ${DOCROOT}/wp-config-tugboat.php
        # Replace wp-config.php with Tugboat version
        - mv ${DOCROOT}/wp-config-tugboat.php ${DOCROOT}/wp-config.php
      build:
        # Import database if it exists
        - if [ -f "${TUGBOAT_ROOT}/database.sql" ]; then mysql --ssl_mode=DISABLED -h mysql -u tugboat -ptugboat tugboat < "${TUGBOAT_ROOT}/database.sql"; fi
        # Install WordPress if no database
        - wp core install --url="https://${TUGBOAT_SERVICE_URL_HOST}" --title="WordPress Site" --admin_user="admin" --admin_password="admin" --admin_email="admin@example.com" --skip-email || /bin/true

  mysql:
    image: tugboatqa/mysql:8-debian
